### ISSUE TITLE
Determine which API inputs to use to grab campaign contributions and expenditures from https://netfile.com/Connect2/api/swagger-ui/#!/public/ByFilingCsv

### ISSUE THREAD

**Issue by tommy-stone** [opensandiego/sdvv-backend#10]

**Comment by nancyheiss** [comment]
@tommy-stone I found something ...
using GET /public/campaign/export/cal201/summary/year/csv
fill in parameters and click the button it generates the URL and shows the response. e.g.
https://netfile.com:443/Connect2/api/public/campaign/export/cal201/summary/year/csv?Aid=32&Year=2020&CurrentPageIndex=1&PageSize=1000&ShowSuperceded=false

[
  {
    "netFileKey": "e20fd3098ac747de9f2dab4b011a0a94",
    "externalId": null,
    "filerLocalId": "CAMPAIGN_CSD-4127",
    "filerStateId": "99-1330",
    "filerName": "SAN DIEGO COUNTY HOTEL-MOTEL ASSOCIATION ISSUE ADVOCACY PAC",
    "filingId": "185715825",
    "filingStartDate": "2020-01-01T00:00:00.0000000-08:00",
    "filingEndDate": "2020-01-18T00:00:00.0000000-08:00",
    "rec_Type": "SMRY",
    "form_Type": "C",
    "line_Item": "1",
    "amount_A": 0,
    "amount_B": null,
    "amount_C": null,
    "elec_Date": null
  },
...
]

So, looks like the response is an array of JSON, not actually a csv, but maybe we can use this. Not sure exactly what data we need. The csv we were downloading had tons of stuff in it but it looks like each thing is a separate request. So maybe we only need to make calls for the exact info we need. This one for transactions looks interesting GET /public/campaign/export/cal201/transaction/year/csv but you need to specify the transaction type. There are several transaction types:

{
  "items": [
    {
      "id": 3,
      "abbreviation": "F401A"
    },
    {
      "id": 15,
      "abbreviation": "F401B"
    },
    {
      "id": 16,
      "abbreviation": "F401B1"
    },
    {
      "id": 17,
      "abbreviation": "F401C"
    },
    {
      "id": 18,
      "abbreviation": "F401D"
    },
    {
      "id": 8,
      "abbreviation": "F450P5"
    },
    {
      "id": 0,
      "abbreviation": "F460A"
    },
    {
      "id": 12,
      "abbreviation": "F460B1"
    },
    {
      "id": 13,
      "abbreviation": "F460B2"
    },
    {
      "id": 1,
      "abbreviation": "F460C"
    },
    {
      "id": 5,
      "abbreviation": "F460D"
    },
    {
      "id": 6,
      "abbreviation": "F460E"
    },
    {
      "id": 11,
      "abbreviation": "F460F"
    },
    {
      "id": 7,
      "abbreviation": "F460G"
    },
    {
      "id": 14,
      "abbreviation": "F460H"
    },
    {
      "id": 2,
      "abbreviation": "F460I"
    },
    {
      "id": 9,
      "abbreviation": "F461P5"
    },
    {
      "id": 10,
      "abbreviation": "F465P3"
    },
    {
      "id": 4,
      "abbreviation": "F496P3"
    },
    {
      "id": 20,
      "abbreviation": "F497P1"
    },
    {
      "id": 21,
      "abbreviation": "F497P2"
    },
    {
      "id": 23,
      "abbreviation": "F498A"
    },
    {
      "id": 22,
      "abbreviation": "F498R"
    },
    {
      "id": 19,
      "abbreviation": "S496"
    },
    {
      "id": -1,
      "abbreviation": "Unset"
    }
  ]
}

**Comment by tommy-stone** [comment]
Sent follow up to netfile who will give us commands to fullfill request

**Comment by robertgz** [comment]
To get as csv 'format=csv' needs to be specified.

http://netfile.com/Connect2/api/public/campaign/export/cal201/transaction/year/csv?Aid=32&Year=2020&CurrentPageIndex=0&PageSize=1000&&ShowSuperceded=false&format=csv

**Comment by tommy-stone** [comment]
Rob has completed this on issue #58
