### ISSUE TITLE
Download jpegs from drive to local directory 

### ISSUE THREAD

**Issue by tommy-stone** [opensandiego/sdvv-backend#6]
1. Download imagse from google drive to downloads/images folder https://drive.google.com/drive/u/2/folders/1jofuld9MEwRr2ZpQjBD2YZZ0tRTCv7xE

**Comment by BolunThompson** [comment]
Is this meant to be a one time download or is it supposed to be updated periodically?
@tommy-stone

**Comment by tommy-stone** [comment]
Closing issue. For now this will be a manual process
