### ISSUE TITLE
Configure function on firebase to execute backend scripts (one function per script)

### ISSUE THREAD

**Issue by tommy-stone** [opensandiego/sdvv-backend#9]
Firebase functions are similar to linux cronjobs. They are what firebases uses to execute independent scripts. We will be using these functions to run the python programs. Functions to execute

1. Google drive download pictures API
2. Download candidate campaign execl file (Nancy working on newest version with API)
3. Extracting data from excel spreadsheet

**Comment by robertgz** [comment]
The back end will run in Heroku and the data update scripts will run there while interacting with a database.
